//
// Aprovacao.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class Aprovacao: NSObject, Codable { 

    public enum Aprovado: String, Codable, CaseIterable {
        case aprovado = "APROVADO"
        case pendente = "PENDENTE"
        case emAnálise = "EM ANÁLISE"
        case indefinido = "INDEFINIDO"
        case criado = "CRIADO"
        case erro = "ERRO"
    }
    /** Estado de aprovação do perfil. */
    public var aprovado: Aprovado? = .indefinido

    public init(aprovado: Aprovado?) {
        self.aprovado = aprovado
    }

}
