//
// Aprovacao.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Aprovacao: Codable {

    public enum Aprovado: String, Codable {
        case aprovado = "APROVADO"
        case pendente = "PENDENTE"
        case emAnálise = "EM ANÁLISE"
        case indefinido = "INDEFINIDO"
    }
    /** Estado de aprovação do perfil. */
    public var aprovado: Aprovado? = .INDEFINIDO

    public init(aprovado: Aprovado?) {
        self.aprovado = aprovado
    }


}

