//
// AssinaturaEletronica.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class AssinaturaEletronica: NSObject, Codable { 

    /** Assinatura eletrônica do usuário. */
    public var assinaturaEletronica: String?

    public init(assinaturaEletronica: String?) {
        self.assinaturaEletronica = assinaturaEletronica
    }

}
