//
// AutenticacaoObjeto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct AutenticacaoObjeto: Codable {

    public var token: String
    public var login: LoginObjeto?

    public init(token: String, login: LoginObjeto?) {
        self.token = token
        self.login = login
    }


}

