//
// AutenticacaoObjeto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct AutenticacaoObjeto: Codable {

    public var token: String

    public init(token: String) {
        self.token = token
    }


}

