//
// AutenticacaoCodigoObjeto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class AutenticacaoCodigoObjeto: NSObject, Codable { 

    public var codigo: String

    public init(codigo: String) {
        self.codigo = codigo
    }

}
