//
// AutenticacaoCodigoObjeto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct AutenticacaoCodigoObjeto: Codable {

    public var codigo: String

    public init(codigo: String) {
        self.codigo = codigo
    }


}

