//
// Confirmado.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Confirmado: Codable {

    /** Estado de confirmação, true caso já tenha sido confirmado, false caso contrário. */
    public var confirmado: Bool?
    /** Mensagem detalhada caso tenha ocorrido algum erro */
    public var erro: String?

    public init(confirmado: Bool?, erro: String?) {
        self.confirmado = confirmado
        self.erro = erro
    }


}

