//
// Documento.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Documentação do Usuário */

public struct Documento: Codable {

    public enum TipoDocumento: String, Codable {
        case carteiraDeHabilitaçãoCnh = "Carteira de Habilitação - CNH"
        case passaporte = "Passaporte"
        case cartIdentEstrangeiroRne = "Cart. Ident. Estrangeiro - RNE"
        case cartIdentidadeProfissional = "Cart. Identidade Profissional"
        case carteiraDeIdentidadeRg = "Carteira de Identidade / RG"
    }
    public var tipoDocumento: TipoDocumento?
    public var numeroDocumento: String?
    /** Orgão expedidor de acordo com o tipo de documento */
    public var orgaoExpedidor: String?
    /** Unidade da Federação onde foi emitido o documeto */
    public var ufEmissao: String?
    /** Data em que o documento foi emitido no formato YYYY-MM-DD (cf. RFC 3339, section 5.8) */
    public var dataEmissao: Date?
    /** Data de validade do documento no formato YYYY-MM-DD (cf. RFC 3339, section 5.8) */
    public var dataValidade: Date?
    /** Código de Segurança da Carteira Nacional de Habilitação */
    public var codigoSegurancaCNH: String?

    public init(tipoDocumento: TipoDocumento?, numeroDocumento: String?, orgaoExpedidor: String?, ufEmissao: String?, dataEmissao: Date?, dataValidade: Date?, codigoSegurancaCNH: String?) {
        self.tipoDocumento = tipoDocumento
        self.numeroDocumento = numeroDocumento
        self.orgaoExpedidor = orgaoExpedidor
        self.ufEmissao = ufEmissao
        self.dataEmissao = dataEmissao
        self.dataValidade = dataValidade
        self.codigoSegurancaCNH = codigoSegurancaCNH
    }


}

