//
// EnvioNovaSenha.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class EnvioNovaSenha: NSObject, Codable { 

    public var cpf: String?
    public var email: String?
    public var senha: String

    public init(cpf: String?, email: String?, senha: String) {
        self.cpf = cpf
        self.email = email
        self.senha = senha
    }

}
