//
// Erro.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Mensagem de erro detalhada */

@objc public class Erro: NSObject, Codable { 

    /** Conteúdo da mensagem de erro. */
    public var mensagem: Any?

    public init(mensagem: Any?) {
        self.mensagem = mensagem
    }

}
