//
// FrontEndStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class FrontEndStep: NSObject, Codable { 

    /** Número positivo inteiro para registrar qual &#39;step&#39; do ponto de vista de UI/front-end o Perfil se encontra. */
    public var step: Double?
    /** Representa o nome da plaforma do front-end. */
    public var platform: String?

    public init(step: Double?, platform: String?) {
        self.step = step
        self.platform = platform
    }

}
