//
// ListaPerfilUsuario.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ListaPerfilUsuario: Codable {

    /** quantidade de elementos que foram retornados */
    public var quantidade: Double?
    /** URL da próxima página de resultados */
    public var proximo: String?
    /** URL da próxima anterior de resultados */
    public var anterior: String?
    /** Lista composta por objetos do tipo Perfil */
    public var resultados: [PerfilUsuario]?

    public init(quantidade: Double?, proximo: String?, anterior: String?, resultados: [PerfilUsuario]?) {
        self.quantidade = quantidade
        self.proximo = proximo
        self.anterior = anterior
        self.resultados = resultados
    }


}

