//
// LoginCriado.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct LoginCriado: Codable {

    public var login: LoginObjeto
    public var token: String

    public init(login: LoginObjeto, token: String) {
        self.login = login
        self.token = token
    }


}

