//
// Pendencia.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class Pendencia: NSObject, Codable { 

    public enum TipoPendencia: String, Codable, CaseIterable {
        case cpf = "cpf"
        case identidade = "identidade"
        case endereco = "endereco"
    }
    public enum StatusPendencia: String, Codable, CaseIterable {
        case registrada = "registrada"
        case documentos = "documentos"
        case enviada = "enviada"
        case analise = "analise"
        case aprovada = "aprovada"
    }
    /** Tipo da pendência: * &#x60;cpf&#x60; - CPF com Pendência * &#x60;identidade&#x60; - Dados Pessoais com Pendência * &#x60;endereco&#x60; - Dados do Endereço com Pendência */
    public var tipoPendencia: TipoPendencia?
    /** Tipo da pendência: * &#x60;registrada&#x60; - Pendência Informada * &#x60;documentos&#x60; - Documentos Recebidos * &#x60;enviada&#x60; - Enviada Para Análise * &#x60;analise&#x60; - Em Análise * &#x60;aprovada&#x60; - Pendência Aprovada */
    public var statusPendencia: StatusPendencia?
    /** Lista de motivos relatados à pendência */
    public var motivos: [String]?

    public init(tipoPendencia: TipoPendencia?, statusPendencia: StatusPendencia?, motivos: [String]?) {
        self.tipoPendencia = tipoPendencia
        self.statusPendencia = statusPendencia
        self.motivos = motivos
    }

}
