//
// SolicitacaoRedefinicaoSenha.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class SolicitacaoRedefinicaoSenha: NSObject, Codable { 

    public var cpf: String?
    public var email: String?
    public var dataNascimento: Date

    public init(cpf: String?, email: String?, dataNascimento: Date) {
        self.cpf = cpf
        self.email = email
        self.dataNascimento = dataNascimento
    }

}
