//
// Submetido.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Submetido: Codable {

    /** Estado de submissão do perfil, true caso já tenha sido submetido, false caso contrário. */
    public var submetido: Bool?

    public init(submetido: Bool?) {
        self.submetido = submetido
    }


}

