//
// DevelopersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire

extension OramaCadastroSwiftAPI {


open class DevelopersAPI {
    /**
     Retorna uma lista composta por objetos do tipo perfil
     
     - parameter limite: (query) Número máximo de elementos (optional)
     - parameter deslocamento: (query) Número de deslocamento (offset) dos elementos (optional)
     - parameter campos: (query) Lista de campos para ser inclusivamente filtrados (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func perfilGet(limite: Double? = nil, deslocamento: Double? = nil, campos: String? = nil, completion: @escaping ((_ data: ListaPerfilUsuario?,_ error: Error?) -> Void)) {
        perfilGetWithRequestBuilder(limite: limite, deslocamento: deslocamento, campos: campos).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Retorna uma lista composta por objetos do tipo perfil
     - GET /perfil/
     - Returna uma lista composta por objetos do tipo perfil
     - BASIC:
       - type: http
       - name: Api-Key
     - parameter limite: (query) Número máximo de elementos (optional)
     - parameter deslocamento: (query) Número de deslocamento (offset) dos elementos (optional)
     - parameter campos: (query) Lista de campos para ser inclusivamente filtrados (optional)
     - returns: RequestBuilder<ListaPerfilUsuario> 
     */
    open class func perfilGetWithRequestBuilder(limite: Double? = nil, deslocamento: Double? = nil, campos: String? = nil) -> RequestBuilder<ListaPerfilUsuario> {
        let path = "/perfil/"
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "limite": limite, 
            "deslocamento": deslocamento, 
            "campos": campos
        ])

        let requestBuilder: RequestBuilder<ListaPerfilUsuario>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
}
