//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire

extension OramaCadastroSwiftAPI {


open class UsersAPI {
    /**
     Autentica um usuário que ainda não é cliente.
     
     - parameter usuarioSenhaObjeto: (body) Dados para autenticação do usuário 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountAutenticacaoPost(usuarioSenhaObjeto: UsuarioSenhaObjeto, completion: @escaping ((_ data: AutenticacaoObjeto?,_ error: Error?) -> Void)) {
        accountAutenticacaoPostWithRequestBuilder(usuarioSenhaObjeto: usuarioSenhaObjeto).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Autentica um usuário que ainda não é cliente.
     - POST /autenticacao/
     - Autentica um usuário que ainda não é cliente, caso o usuário não existe, ou a combinação de usuário e senha ou ainda o usuário já seja cliente retorna um erro.
     - BASIC:
       - type: http
       - name: JWT
     - parameter usuarioSenhaObjeto: (body) Dados para autenticação do usuário 
     - returns: RequestBuilder<AutenticacaoObjeto> 
     */
    open class func accountAutenticacaoPostWithRequestBuilder(usuarioSenhaObjeto: UsuarioSenhaObjeto) -> RequestBuilder<AutenticacaoObjeto> {
        let path = "/autenticacao/"
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: usuarioSenhaObjeto)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<AutenticacaoObjeto>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     * enum for parameter tipoDocumento
     */
    public enum TipoDocumento_accountDocumentoConfirmacaoGet: String {
        case carteiraDeHabilitaçãoCnh = "Carteira de Habilitação - CNH"
        case passaporte = "Passaporte"
        case cartIdentEstrangeiroRne = "Cart. Ident. Estrangeiro - RNE"
        case cartIdentidadeProfissional = "Cart. Identidade Profissional"
        case carteiraDeIdentidadeRg = "Carteira de Identidade / RG"
        case comprovanteBancário = "Comprovante Bancário"
        case comprovanteDeResidência = "Comprovante de Residência"
    }

    /**
     Consulta o status de confirmação do documento que foi submetido
     
     - parameter cpf: (path) CPF do perfil 
     - parameter tipoDocumento: (query) Tipo do documento 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountDocumentoConfirmacaoGet(cpf: String, tipoDocumento: TipoDocumento_accountDocumentoConfirmacaoGet, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountDocumentoConfirmacaoGetWithRequestBuilder(cpf: cpf, tipoDocumento: tipoDocumento).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Consulta o status de confirmação do documento que foi submetido
     - GET /perfil/{cpf}/documento/confirmacao/
     - Consulta o status de confirmação do documento que foi submetido
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - parameter tipoDocumento: (query) Tipo do documento 
     - returns: RequestBuilder<Void> 
     */
    open class func accountDocumentoConfirmacaoGetWithRequestBuilder(cpf: String, tipoDocumento: TipoDocumento_accountDocumentoConfirmacaoGet) -> RequestBuilder<Void> {
        var path = "/perfil/{cpf}/documento/confirmacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "tipoDocumento": tipoDocumento.rawValue
        ])

        let requestBuilder: RequestBuilder<Void>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter tipoDocumento
     */
    public enum TipoDocumento_accountDocumentoPut: String {
        case carteiraDeHabilitaçãoCnh = "Carteira de Habilitação - CNH"
        case passaporte = "Passaporte"
        case cartIdentEstrangeiroRne = "Cart. Ident. Estrangeiro - RNE"
        case cartIdentidadeProfissional = "Cart. Identidade Profissional"
        case carteiraDeIdentidadeRg = "Carteira de Identidade / RG"
        case comprovanteBancário = "Comprovante Bancário"
        case comprovanteDeResidência = "Comprovante de Residência"
    }

    /**
     Anexa ou atualiza documento para conferencia de autenticidade do perfil.
     
     - parameter cpf: (path) CPF do perfil 
     - parameter tipoDocumento: (query) Tipo do documento 
     - parameter name: (form) Nome do atributo codificado em form-data &#39;image&#39; 
     - parameter filename: (form) Arquivo binário que será enviado. O formato deve ser PDF, PNG ou JPG 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountDocumentoPut(cpf: String, tipoDocumento: TipoDocumento_accountDocumentoPut, name: String, filename: URL, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountDocumentoPutWithRequestBuilder(cpf: cpf, tipoDocumento: tipoDocumento, name: name, filename: filename).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Anexa ou atualiza documento para conferencia de autenticidade do perfil.
     - PUT /perfil/{cpf}/documento/
     - Anexa ou atualiza documento que será usado no processo conferencia de autenticidade do perfil. É recomendado fazer o upload de documentos para comprovação de identidade. Caso o perfil tiver conta bancária conjunta ou a conta seja do banco Itaú é recomendado o upload do documento 'Comprovante Bancário'.
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - parameter tipoDocumento: (query) Tipo do documento 
     - parameter name: (form) Nome do atributo codificado em form-data &#39;image&#39; 
     - parameter filename: (form) Arquivo binário que será enviado. O formato deve ser PDF, PNG ou JPG 
     - returns: RequestBuilder<Void> 
     */
    open class func accountDocumentoPutWithRequestBuilder(cpf: String, tipoDocumento: TipoDocumento_accountDocumentoPut, name: String, filename: URL) -> RequestBuilder<Void> {
        var path = "/perfil/{cpf}/documento/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let formParams: [String:Any?] = [
            "name": name,
            "filename": filename
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "tipoDocumento": tipoDocumento.rawValue
        ])

        let requestBuilder: RequestBuilder<Void>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Cria um login para usuário.
     
     - parameter loginSenhaObjeto: (body) Dados para criação do login 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountIdentificacaoPost(loginSenhaObjeto: LoginSenhaObjeto, completion: @escaping ((_ data: LoginCriado?,_ error: Error?) -> Void)) {
        accountIdentificacaoPostWithRequestBuilder(loginSenhaObjeto: loginSenhaObjeto).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Cria um login para usuário.
     - POST /identificacao/
     - Cria um novo login que será usado para acesso ao sistema.
     - parameter loginSenhaObjeto: (body) Dados para criação do login 
     - returns: RequestBuilder<LoginCriado> 
     */
    open class func accountIdentificacaoPostWithRequestBuilder(loginSenhaObjeto: LoginSenhaObjeto) -> RequestBuilder<LoginCriado> {
        let path = "/identificacao/"
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginSenhaObjeto)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<LoginCriado>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Retorna o estado de aprovação de um perfil
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilAprovacaoGet(cpf: String, completion: @escaping ((_ data: Aprovacao?,_ error: Error?) -> Void)) {
        accountPerfilAprovacaoGetWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Retorna o estado de aprovação de um perfil
     - GET /perfil/{cpf}/aprovacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Aprovacao> 
     */
    open class func accountPerfilAprovacaoGetWithRequestBuilder(cpf: String) -> RequestBuilder<Aprovacao> {
        var path = "/perfil/{cpf}/aprovacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Aprovacao>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Estado atual de confirmação do celular
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilCelularAutenticacaoConfirmacaoGet(cpf: String, completion: @escaping ((_ data: Confirmado?,_ error: Error?) -> Void)) {
        accountPerfilCelularAutenticacaoConfirmacaoGetWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Estado atual de confirmação do celular
     - GET /perfil/{cpf}/celular/autenticacao/confirmacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Confirmado> 
     */
    open class func accountPerfilCelularAutenticacaoConfirmacaoGetWithRequestBuilder(cpf: String) -> RequestBuilder<Confirmado> {
        var path = "/perfil/{cpf}/celular/autenticacao/confirmacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Confirmado>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gera um código para iniciar o processo de validação do número do celular
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilCelularAutenticacaoPost(cpf: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountPerfilCelularAutenticacaoPostWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Gera um código para iniciar o processo de validação do número do celular
     - POST /perfil/{cpf}/celular/autenticacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Void> 
     */
    open class func accountPerfilCelularAutenticacaoPostWithRequestBuilder(cpf: String) -> RequestBuilder<Void> {
        var path = "/perfil/{cpf}/celular/autenticacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Confirma o numero de celular, concluindo a validação
     
     - parameter cpf: (path) CPF do perfil 
     - parameter codigo: (query) Código de validação para confirmar o número de celular 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilCelularConfirmacaoPost(cpf: String, codigo: String, completion: @escaping ((_ data: Confirmado?,_ error: Error?) -> Void)) {
        accountPerfilCelularConfirmacaoPostWithRequestBuilder(cpf: cpf, codigo: codigo).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Confirma o numero de celular, concluindo a validação
     - POST /perfil/{cpf}/celular/autenticacao/confirmacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - parameter codigo: (query) Código de validação para confirmar o número de celular 
     - returns: RequestBuilder<Confirmado> 
     */
    open class func accountPerfilCelularConfirmacaoPostWithRequestBuilder(cpf: String, codigo: String) -> RequestBuilder<Confirmado> {
        var path = "/perfil/{cpf}/celular/autenticacao/confirmacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "codigo": codigo
        ])

        let requestBuilder: RequestBuilder<Confirmado>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Estado atual de confirmação do email
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilEmailAutenticacaoConfirmacaoGet(cpf: String, completion: @escaping ((_ data: Confirmado?,_ error: Error?) -> Void)) {
        accountPerfilEmailAutenticacaoConfirmacaoGetWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Estado atual de confirmação do email
     - GET /perfil/{cpf}/email/autenticacao/confirmacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Confirmado> 
     */
    open class func accountPerfilEmailAutenticacaoConfirmacaoGetWithRequestBuilder(cpf: String) -> RequestBuilder<Confirmado> {
        var path = "/perfil/{cpf}/email/autenticacao/confirmacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Confirmado>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Gera um código para iniciar o processo de validação do email
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilEmailAutenticacaoPost(cpf: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountPerfilEmailAutenticacaoPostWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Gera um código para iniciar o processo de validação do email
     - POST /perfil/{cpf}/email/autenticacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Void> 
     */
    open class func accountPerfilEmailAutenticacaoPostWithRequestBuilder(cpf: String) -> RequestBuilder<Void> {
        var path = "/perfil/{cpf}/email/autenticacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Confirma o email, concluindo a validação
     
     - parameter cpf: (path) CPF do perfil 
     - parameter codigo: (query) Código de validação para confirmar o email 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilEmailConfirmacaoPost(cpf: String, codigo: String, completion: @escaping ((_ data: Confirmado?,_ error: Error?) -> Void)) {
        accountPerfilEmailConfirmacaoPostWithRequestBuilder(cpf: cpf, codigo: codigo).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Confirma o email, concluindo a validação
     - POST /perfil/{cpf}/email/autenticacao/confirmacao/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - parameter codigo: (query) Código de validação para confirmar o email 
     - returns: RequestBuilder<Confirmado> 
     */
    open class func accountPerfilEmailConfirmacaoPostWithRequestBuilder(cpf: String, codigo: String) -> RequestBuilder<Confirmado> {
        var path = "/perfil/{cpf}/email/autenticacao/confirmacao/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "codigo": codigo
        ])

        let requestBuilder: RequestBuilder<Confirmado>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Retorna o perfil de um usuário que ainda não foi transformado em cliente.
     
     - parameter cpf: (path) CPF do perfil 
     - parameter campos: (query) Lista de campos para ser inclusivamente filtrados (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilGet(cpf: String, campos: String? = nil, completion: @escaping ((_ data: PerfilUsuario?,_ error: Error?) -> Void)) {
        accountPerfilGetWithRequestBuilder(cpf: cpf, campos: campos).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Retorna o perfil de um usuário que ainda não foi transformado em cliente.
     - GET /perfil/{cpf}/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - parameter campos: (query) Lista de campos para ser inclusivamente filtrados (optional)
     - returns: RequestBuilder<PerfilUsuario> 
     */
    open class func accountPerfilGetWithRequestBuilder(cpf: String, campos: String? = nil) -> RequestBuilder<PerfilUsuario> {
        var path = "/perfil/{cpf}/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "campos": campos
        ])

        let requestBuilder: RequestBuilder<PerfilUsuario>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Submete o perfil de usuário associado a um login para ser criado como cliente.
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilPost(cpf: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountPerfilPostWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Submete o perfil de usuário associado a um login para ser criado como cliente.
     - POST /perfil/{cpf}/
     - Submete o perfil de usuário associado a um login para ser criado como cliente. É necessário validar ambos o número do celular e o e-mail para que a submissão seja aceita, veja os endpoints /perfil/{cpf}/celular/autenticacao/ e /perfil/{cpf}/email/autenticacao/. Após submissão deste POST, o perfil não poderá mais ser alterado. Para alterar ou inserir informações no perfil antes de submeter o perfil o método PUT deve ser utilizado.
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Void> 
     */
    open class func accountPerfilPostWithRequestBuilder(cpf: String) -> RequestBuilder<Void> {
        var path = "/perfil/{cpf}/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Atualiza perfil para criação de conta.
     
     - parameter cpf: (path) CPF do perfil 
     - parameter perfilUsuario: (body) Dados para criação ou atualização do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilPut(cpf: String, perfilUsuario: PerfilUsuario, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountPerfilPutWithRequestBuilder(cpf: cpf, perfilUsuario: perfilUsuario).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }

    /**
     Atualiza perfil para criação de conta.
     - PUT /perfil/{cpf}/
     - Atualiza um perfil de usuário associado a um login para o processo de criação de um usuário. Cada chamada modifica o perfil. Quando o perfil estiver pronto para ser submetido para criação de conta, basta enviar um POST.
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - parameter perfilUsuario: (body) Dados para criação ou atualização do perfil 
     - returns: RequestBuilder<Void> 
     */
    open class func accountPerfilPutWithRequestBuilder(cpf: String, perfilUsuario: PerfilUsuario) -> RequestBuilder<Void> {
        var path = "/perfil/{cpf}/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: perfilUsuario)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Retorna o estado de submissão de um perfil
     
     - parameter cpf: (path) CPF do perfil 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountPerfilSubmetidoGet(cpf: String, completion: @escaping ((_ data: Submetido?,_ error: Error?) -> Void)) {
        accountPerfilSubmetidoGetWithRequestBuilder(cpf: cpf).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Retorna o estado de submissão de um perfil
     - GET /perfil/{cpf}/submetido/
     - BASIC:
       - type: http
       - name: JWT
     - parameter cpf: (path) CPF do perfil 
     - returns: RequestBuilder<Submetido> 
     */
    open class func accountPerfilSubmetidoGetWithRequestBuilder(cpf: String) -> RequestBuilder<Submetido> {
        var path = "/perfil/{cpf}/submetido/"
        let cpfPreEscape = "\(APIHelper.mapValueToPathItem(cpf))"
        let cpfPostEscape = cpfPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{cpf}", with: cpfPostEscape, options: .literal, range: nil)
        let URLString = OramaCadastroSwiftAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Submetido>.Type = OramaCadastroSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
}
